POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWUyIiwiaWQiOiI2MmUyNzkyODQ0OTM0MTU3MGQ2ZDljNzgiLCJpYXQiOjE2NTkwMTM0NDh9.eqVrZKAWdQgMRrLlFl28FLpwx0BC80ErQ8IsFoPC8bY

{
  "title": "Blog3",
  "author": "Someone3",
  "url": "www.test3.fi",
  "likes": 3
}